---
- name: Converge
  hosts: all
  become: true

  vars:
    # Role: rhsm
    rhsm_username: "{{ lookup('env', 'RHSM_USERNAME') }}"
    rhsm_password: "{{ lookup('env', 'RHSM_PASSWORD') }}"
    rhsm_auto_attach: true
    rhsm_server_proxy_hostname: "{{ lookup('env', 'http_proxy_hostname') }}"
    rhsm_server_proxy_port: "{{ lookup('env', 'http_proxy_port') }}"
    rhsm_server_proxy_user: "{{ lookup('env', 'http_proxy_user') }}"
    rhsm_server_proxy_password: "{{ lookup('env', 'http_proxy_password') }}"
    rhsm_consumer_name: "nycrecords_{{ '%Y%m%d_%H%M%s' | strftime(ansible_date_time.epoch) }}"
    rhsm_repositories:
      enabled:
        - rhel-7-server-rpms
        - rhel-7-server-optional-rpms
        - rhel-7-server-extras-rpms
        - rhel-server-rhscl-7-rpms

    # Role: java
    java_home: /usr/lib/jvm/java-1.8.0-openjdk.x86_64

  roles:
    - role: nycrecords.rhsm
    - role: nycrecords.java
    - role: ansible-role-libreoffice
